version: '3'
services:
  registry:
    restart: always
    image: registry:2.7
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_SECRET: secret
      REGISTRY_STORAGE_DELETE_ENABLED: 'True'
    ports:
      - "127.0.0.1:${REGISTRY_LISTEN_PORT}:5000"
    volumes:
      - registry:/var/lib/registry
      - registry-auth:/auth
#      - "./config.yml:/etc/docker/registry/config.yml"
    networks:
    - registry
  webui:
    restart: always
    image: joxit/docker-registry-ui:static
    environment:
      URL: https://${REGISTRY_NAME}
      REGISTRY_URL: http://registry:5000
      REGISTRY_NAME: ${REGISTRY_NAME}
      REGISTRY_TITLE: ${REGISTRY_NAME}
    ports:
    - "127.0.0.1:${UI_LISTEN_PORT}:80"
    networks:
    - registry
volumes:
  registry:
  registry-auth:
    driver_opts:
      type: none
      device: "${PWD}/auth"
      o: bind
networks:
  registry:
