version: '3'
services:
  registry:
    image: ${IMAGE}
    build:
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
        no_proxy: ${NO_PROXY}
      context: .
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_SECRET: secret
      REGISTRY_STORAGE_DELETE_ENABLED: 'True'
    ports:
    - "${REGISTRY_LISTEN_PORT}:5000"
    volumes:
    - registry:/var/lib/registry
    - registry-auth:/auth
    networks:
    - network
  webui:
    image: joxit/docker-registry-ui:static
    environment:
      URL: https://${REGISTRY_NAME}
      REGISTRY_URL: http://registry:5000
      REGISTRY_NAME: ${REGISTRY_NAME}
      REGISTRY_TITLE: ${REGISTRY_NAME}
      PULL_URL: https://${REGISTRY_NAME}:5000
      DELETE_IMAGES: "true"
    ports:
    - "${UI_LISTEN_PORT}:80"
    networks:
    - network
volumes:
  registry: {}
  registry-auth: {}
networks:
  network: {}
